spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cbdtodo"
    username: "root"
    password: "!rlaxodn12"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernates:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect